services:
  frontend:
    image: gnagchat-frontend
    container_name: gnagchat_frontend
    env_file:
      - .env
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    restart: unless-stopped
  backend:
    image: gnagchat-backend
    container_name: gnagchat_backend
    env_file:
      - .env
    networks:
      - gnagchat
    ports:
      - "8081:3000"
    volumes:
      - gnagchat_data:/app/backend/data
    restart: unless-stopped

volumes:
  gnagchat_data:
    driver: local

networks:
  gnagchat:
    driver: bridge